typography_spectrum: 0.03779466124251485
color:
  brandStrength: 0.37470884062349796
  lightness: 0.7580789893399924
  saturation: 0.13943471433594823
  rhythmicContrast: 0.9431564051192254
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.6817514149006456
name: Woven Figure
title: PostmodernHR
description: Objects In Mirror Are Behind You
